openapi: 3.0.3
info:
  version: "1.0.0"
  title: My Awesome API
servers:
  - url: "http://localhost:8000"
    description: Local development server
paths:
  /api/users/me:
    $ref: users/me.yaml
components:
  securitySchemes:
    GESSO:
      type: apiKey
      in: header
      name: sso_uid
